+define+SIMULATION
+define+SHORT_SIM
+define+BFM_ASSERTIONS
-incr

../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/sim/xil_pcie_wrapper_ipi_pcie_7x_0_0.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_rx.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_rx_null_gen.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_rx_pipeline.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_top.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_tx.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_tx_pipeline.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_axi_basic_tx_thrtl_ctl.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_core_top.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gt_common.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gt_rx_valid_filter_7x.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gt_top.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gt_wrapper.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gtp_cpllpd_ovrd.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gtp_pipe_drp.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gtp_pipe_rate.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gtp_pipe_reset.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_gtx_cpllpd_ovrd.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_7x.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_bram_7x.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_bram_top_7x.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_brams_7x.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_pipe_lane.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_pipe_misc.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_pipe_pipeline.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie_top.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pcie2_top.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_clock.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_drp.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_eq.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_rate.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_reset.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_sync.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_user.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_pipe_wrapper.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_qpll_drp.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_qpll_reset.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_qpll_wrapper.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_pcie_7x_0_0/source/xil_pcie_wrapper_ipi_pcie_7x_0_0_rxeq_scan.v
../nwl_ip/rtl/dma_back_end_axi.vp
../rtl_ref_design/ref_tiny_fifo.v
../rtl_ref_design/ref_dc_fifo.v
../rtl_ref_design/ref_inferred_shallow_ram.v
../rtl_ref_design/ref_dc_fifo_adv_block_ram.v
../rtl_ref_design/ref_sc_fifo_shallow_ram.v
../rtl_ref_design/ref_dc_fifo_shallow_ram.v
../rtl_ref_design/ref_dc_fifo_block_ram.v
../rtl_ref_design/ref_inferred_block_ram.v
../rtl_ref_design/register_example_axi.v
../rtl_ref_design/t_example.v
../rtl_ref_design/packet_check_axi.v
../rtl_ref_design/packet_gen_axi.v
../rtl_ref_design/dma_ref_design_axi.v
../rtl_ref_design/ref_gray_sync_bus.v
../rtl_ref_design/ref_bin_to_gray.v
../rtl_ref_design/sdram_dma_ref_design_axi.v
../rtl_ref_design/ref_gray_to_bin.v
../rtl_ref_design/sram_mp_axi.v
../rtl_ref_design/util_sync_bus.v
../rtl_ref_design/util_sync_flops.v
../rtl_ref_design/util_toggle_pos_sync.v
../nwl_ip/rtl/nwl_axi_dma_wrapper.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_NWL_AXI_Ref_Des_0_0/synth/xil_pcie_wrapper_ipi_NWL_AXI_Ref_Des_0_0.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/ip/xil_pcie_wrapper_ipi_NWL_AXI_DMA_0_0/synth/xil_pcie_wrapper_ipi_NWL_AXI_DMA_0_0.v
../route/ipi_prj.srcs/sources_1/bd/xil_pcie_wrapper_ipi/hdl/xil_pcie_wrapper_ipi.v
../models/pcie_bfm_x4.v
../models/bfm_pcie_core_vc1.vp
report_assertions.v
ref_design_ts.v
tb_top.v
direct_dma_bfm.v
glbl.v

