// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsobel_filter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSobel_filter_CfgInitialize(XSobel_filter *InstancePtr, XSobel_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSobel_filter_Start(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSobel_filter_IsDone(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSobel_filter_IsIdle(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSobel_filter_IsReady(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSobel_filter_EnableAutoRestart(XSobel_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSobel_filter_DisableAutoRestart(XSobel_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XSobel_filter_SetRows(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XSobel_filter_GetRows(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XSobel_filter_SetCols(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XSobel_filter_GetCols(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XSobel_filter_SetC_xr0c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA, Data);
}

u32 XSobel_filter_GetC_xr0c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA);
    return Data;
}

void XSobel_filter_SetC_xr0c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA, Data);
}

u32 XSobel_filter_GetC_xr0c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA);
    return Data;
}

void XSobel_filter_SetC_xr0c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA, Data);
}

u32 XSobel_filter_GetC_xr0c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA);
    return Data;
}

void XSobel_filter_SetC_xr1c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA, Data);
}

u32 XSobel_filter_GetC_xr1c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA);
    return Data;
}

void XSobel_filter_SetC_xr1c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA, Data);
}

u32 XSobel_filter_GetC_xr1c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA);
    return Data;
}

void XSobel_filter_SetC_xr1c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA, Data);
}

u32 XSobel_filter_GetC_xr1c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA);
    return Data;
}

void XSobel_filter_SetC_xr2c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA, Data);
}

u32 XSobel_filter_GetC_xr2c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA);
    return Data;
}

void XSobel_filter_SetC_xr2c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA, Data);
}

u32 XSobel_filter_GetC_xr2c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA);
    return Data;
}

void XSobel_filter_SetC_xr2c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA, Data);
}

u32 XSobel_filter_GetC_xr2c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA);
    return Data;
}

void XSobel_filter_SetC_yr0c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA, Data);
}

u32 XSobel_filter_GetC_yr0c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA);
    return Data;
}

void XSobel_filter_SetC_yr0c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA, Data);
}

u32 XSobel_filter_GetC_yr0c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA);
    return Data;
}

void XSobel_filter_SetC_yr0c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA, Data);
}

u32 XSobel_filter_GetC_yr0c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA);
    return Data;
}

void XSobel_filter_SetC_yr1c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA, Data);
}

u32 XSobel_filter_GetC_yr1c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA);
    return Data;
}

void XSobel_filter_SetC_yr1c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA, Data);
}

u32 XSobel_filter_GetC_yr1c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA);
    return Data;
}

void XSobel_filter_SetC_yr1c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA, Data);
}

u32 XSobel_filter_GetC_yr1c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA);
    return Data;
}

void XSobel_filter_SetC_yr2c0(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA, Data);
}

u32 XSobel_filter_GetC_yr2c0(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA);
    return Data;
}

void XSobel_filter_SetC_yr2c1(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA, Data);
}

u32 XSobel_filter_GetC_yr2c1(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA);
    return Data;
}

void XSobel_filter_SetC_yr2c2(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA, Data);
}

u32 XSobel_filter_GetC_yr2c2(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA);
    return Data;
}

void XSobel_filter_SetC_high_thesh(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_HIGH_THESH_DATA, Data);
}

u32 XSobel_filter_GetC_high_thesh(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_HIGH_THESH_DATA);
    return Data;
}

void XSobel_filter_SetC_low_thresh(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA, Data);
}

u32 XSobel_filter_GetC_low_thresh(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA);
    return Data;
}

void XSobel_filter_SetC_invert(XSobel_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA, Data);
}

u32 XSobel_filter_GetC_invert(XSobel_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA);
    return Data;
}

void XSobel_filter_InterruptGlobalEnable(XSobel_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_GIE, 1);
}

void XSobel_filter_InterruptGlobalDisable(XSobel_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_GIE, 0);
}

void XSobel_filter_InterruptEnable(XSobel_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_IER);
    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XSobel_filter_InterruptDisable(XSobel_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_IER);
    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XSobel_filter_InterruptClear(XSobel_filter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XSobel_filter_InterruptGetEnabled(XSobel_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_IER);
}

u32 XSobel_filter_InterruptGetStatus(XSobel_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_FILTER_CONTROL_BUS_ADDR_ISR);
}

